DROP DATABASE IF EXISTS FINANCE;

CREATE DATABASE IF NOT EXISTS FINANCE;

USE FINANCE;

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
	TID BIGINT NOT NULL AUTO_INCREMENT,   
	T_DATE DATE NOT NULL, 
	T_TYPE CHAR(1) NOT NULL,
	CATEGORY VARCHAR(255) NOT NULL, 
	AMOUNT DECIMAL(8,2) NOT NULL DEFAULT 0.0, 
	PRIMARY KEY(TID)
);

CREATE TABLE IF NOT EXISTS BUDGET_ITEMS (
	ID BIGINT NOT NULL AUTO_INCREMENT, 
	START_DATE DATE NOT NULL, 
	END_DATE DATE NOT NULL, 
	ITEM_TYPE CHAR(1) NOT NULL, 
	CATEGORY VARCHAR(255) NOT NULL, 
	AMOUNT DECIMAL(8,2) NOT NULL DEFAULT 0.0, 
	PRIMARY KEY(ID)
);

DROP USER 'finance-web'@'localhost';
DROP USER 'finance-web'@'%';
CREATE USER 'finance-web'@'localhost' IDENTIFIED BY 'tpass';
CREATE USER 'finance-web'@'%' IDENTIFIED BY 'tpass';
GRANT INSERT, SELECT, UPDATE, DELETE ON FINANCE.BUDGET_ITEMS TO 'finance-web'@'%' IDENTIFIED BY 'tpass';
GRANT INSERT, SELECT, UPDATE, DELETE ON FINANCE.TRANSACTIONS TO 'finance-web'@'%' IDENTIFIED BY 'tpass';

CREATE INDEX T_DATE_INDEX ON TRANSACTIONS(T_DATE);
CREATE INDEX B_ITEM_ST_DT_IDX ON BUDGET_ITEMS(START_DATE);
CREATE INDEX B_ITEM_END_DT_IDX ON BUDGET_ITEMS(END_DATE);
